---
- hosts: switches
  gather_facts: no

  tasks:
    - name: Remove the login banner
      cisco.ios.ios_config:
        lines: no banner login

    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        multiline_delimiter: ^
        text: "{{ lookup('file', '../configurations/banner.cfg') }}"
        state: present

    - name: save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified